import Head from "next/head";

export default function Home() {
  return (
    <div className="h-screen w-screen flex items-center justify-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className="text-7xl font-bold">This is the new portfolio</p>
    </div>
  );
}
